<script lang="ts">
  let cat;

  function get() {
    cat = fetch('https://thatcopy.pw/catapi/rest/').then((x) => x.json());
  }

  get();
</script>

<p>ive been busy doing internal stuff and working on the toolkit. also taking breaks and stuff.</p>

<p>
  i will give you something here though. a photo of a cat that was randomly generated by a
  thirdparty api.
</p>

{#await cat}
  <div><strong>Loading</strong></div>
{:then json}
  <div>
    <img src={json.webpurl} alt="Random Cat" on:click={get} />
  </div>
{/await}

<style>
  p,
  div {
    margin: 1rem 2rem;
  }

  img {
    width: 400px;
  }
</style>
